### ISSUE TITLE
Possible typo in the Hoare logic chapter

### ISSUE THREAD

**Issue by co-dan** [achlipala/frap#14]
I am talking about the statement of Lemma 10.1 on page 65: https://github.com/achlipala/frap/blob/master/frap_book.tex#L2782

Should it be `$\denote{b}(h, v)$` instead of `$\denote{b}(h, s)$`?

Best regards,
-Dan

**Comment by achlipala** [comment]
Yeah, that was indeed a typo.  I've fixed it now.  Thanks for the report!
