### ISSUE TITLE
Typo in ch. 13.3?

### ISSUE THREAD

**Issue by larsr** [achlipala/frap#15]
[In the code](https://github.com/achlipala/frap/blob/512f585d904fbfaedc515c1832227741fe1352d7/SharedMemory.v#L517) and on [p. 78, `commutes(_,_)`](https://github.com/achlipala/frap/blob/512f585d904fbfaedc515c1832227741fe1352d7/frap_book.tex#L3595) is defined to take two arguments: an atomic action and a summary. 

But on [p. 79 (the first line)](https://github.com/achlipala/frap/blob/512f585d904fbfaedc515c1832227741fe1352d7/frap_book.tex#L3616)   `commutes(c_0, c_1)` is called with two atomic actions.  

Should the second argument instead be the summary `s` (as in the proof of [`commutes_sound`](https://github.com/achlipala/frap/blob/512f585d904fbfaedc515c1832227741fe1352d7/SharedMemory.v#L689))?

**Comment by achlipala** [comment]
Yeah, that was a mistake, which is fixed now.  Thanks for the report.
