### ISSUE TITLE
Minor typo in section 2.5

### ISSUE THREAD

**Issue by blakeelias** [achlipala/frap#17]
In section 2.5, "Simplification and Rewriting", there is a minor typo. The sentence:

`We may apply the defining equation to rewrite into a different formula, where we have essential pushed the definition of $\size{\cdot}$ through the $\mathsf{Plus}$.`

should read:

`We may apply the defining equation to rewrite into a different formula, where we have essentially pushed the definition of $\size{\cdot}$ through the $\mathsf{Plus}$.`

**Comment by blakeelias** [comment]
(The word "essential" should be "essentially". Not sure how much you care about these types of issues for the moment, but anyway, here it is!)

**Comment by achlipala** [comment]
Thanks.  I do indeed care about fixing that kind of typo.  The version I post after class today will include this fix.
