### ISSUE TITLE
Failing to compile Sets.v

### ISSUE THREAD

**Issue by baz1** [achlipala/frap#24]
Hi,

I tried to compile the library with `make lib`, but this failed at the following step:

```none
coqc  -q  -R . Frap   Sets
File "/[...]/frap/Sets.v", line 312, characters 23-22:
Syntax error: [constr:operconstr] expected after '=' (in [constr:operconstr]).
Makefile.coq:245: recipe for target 'Sets.vo' failed
make[1]: *** [Sets.vo] Error 1
make[1]: Leaving directory '/[...]/frap'
Makefile:16: recipe for target 'lib' failed
make: *** [lib] Error 2
```

Could it be because this library requires a version of Coq newer than 8.4pl4 ? (this is the current version for Ubuntu, which does date back a bit)
Thank you

Remi

**Comment by achlipala** [comment]
Yes, sorry: I had to move up the required Coq version, since newer versions broke backwards compatibility.
