### ISSUE TITLE
Cannot find library Frap in loadpath

### ISSUE THREAD

**Issue by mheiber** [achlipala/frap#32]
With a fresh clone, on Windows 10, tested with Coq versions 8.4 and 8.10:

make -C frap lib # OK
make -C pset1 # Error

The error is:

```
make: Entering directory '/c/dev-other/frap/pset1'
coqc -q -R ../frap Frap Pset1Sig
File "C:\dev-other\frap\pset1/Pset1Sig.v", line 3, characters 0-20:
Error: Cannot find library Frap in loadpath
make: *** [Makefile:6: coq] Error 1
make: Leaving directory '/c/dev-other/frap/pset1'
```

Advice welcome! I'm really hoping to take a stab at these exercises

**Comment by achlipala-biz** [comment]
This bug report doesn't seem to be self-contained, as this repo contains no `pset1`, right?

**Comment by aymanosman** [comment]
Looks like you want to perform those actions on this repo https://github.com/mit-frap/spring18.

**Comment by mheiber** [comment]
sorry, wrong repo, thanks
