### ISSUE TITLE
Typo in Polymorphism.v

### ISSUE THREAD

**Issue by bkushigian** [achlipala/frap#41]
In [lines 18-22 of Polymorphism.v](https://github.com/achlipala/frap/blob/583605fded281ad725bcb3f7a6f8741b36567ce1/Polymorphism.v#L18-L22) there is a typo describing `option`. I'd do a PR but I'm not quite sure what it should say:

> While Java and friends force all sorts of different types to include the special value [null],
> in Coq we request that option explicitly **[something here]** by wrapping a type in [option].

**Comment by p0llard** [comment]
I don't think this is a typo; if you replace 'that' with 'this' it might be easier to parse. The first occurrence of the word option is using it in its normal, dictionary definition sense.

**Comment by achlipala** [comment]
This could be a corner case of the way I perceive English, but the original sounds fine to me.  The word "explicitly" is an adverb modifying "request."

**Comment by p0llard** [comment]
@achlipala I think if there's any ambiguity, it's that the first occurrence of the word "option" might be referring to the type `option`, in which case we might expect a verb phrase in the place of [something here].

**Comment by bkushigian** [comment]
No no, you're right, this was a parse error on my part
