### ISSUE TITLE
"make clean" deletes book source

### ISSUE THREAD

**Issue by corwin-of-amber** [achlipala/frap#5]
On Mac OS X, the default filesystem is case-insensitive.
This is unfortunate.
Since `Frap.v` is present, `make clean` tries to delete `Frap.tex`, which results in deleting `frap.tex`.

**Comment by cpitclaudel** [comment]
Fixed by #4, right?

**Comment by corwin-of-amber** [comment]
Yeah that sure seems to fix it.

**Comment by achlipala** [comment]
OK, then I think it's all better now.  Thanks for the report.
